### ISSUE TITLE
Delete stale data from blobfs

### ISSUE THREAD

**Issue by mansu** [slackhq/astra#210]
Currently, blobfs can have additional objects that are not tracked by our metadata store. This can happen when an indexer service uploads files to S3 but fails to create a metadata entry for it.

Create a new service in cluster manager that compares the data from blob store with the metadata, and deletes any data from blobfs that shouldn't exist.

For cloud stores like AWS S3 and Azure blob store, we can use life cycle policies to automatically prune this data after some time. So, this functionality is more critical for stores like HDFS.

**Comment by bryanlb** [comment]
Experimental work for computing the delta between object storage and the metadata was done in https://github.com/slackhq/kaldb/commit/7ec2ff213b4ecd4c3e5da96fef3e12a8660d2592. This effort was postponed due to the fact this is primarily intended to cover what should be an exceptional situation. For cloud-based object stores this can be resolved more easily with lifecycle policies, so this functionality would only be necessary for blob storage options like HDFS.
